### ISSUE TITLE
Add Run or Start button on Device Tab for manually force action

### ISSUE THREAD

**Issue by tOOmki** [enesbcs/rpieasy#103]
Add "Run" or "Start" button on Devices tab for manually force action.

**Comment by enesbcs** [comment]
you mean, that make a button for the long-time existing command "taskrun,<tasknumber>" ?

**Comment by tOOmki** [comment]
yes.

**Comment by TD-er** [comment]
That's a very nice idea also for ESPEasy.

**Comment by enesbcs** [comment]
Added Run button on enabled devices at commit https://github.com/enesbcs/rpieasy/commit/fa70fc360fb01a408d7db2e37e4277866f6e8525

**Comment by tOOmki** [comment]
Work good :D
