### ISSUE TITLE
Docker image for RPIEasy

### ISSUE THREAD

**Issue by happytm** [enesbcs/rpieasy#104]
I have recommended RPIEasy for docker image. This is just for your information.

https://github.com/gcgarner/IOTstack/issues/10

https://www.youtube.com/watch?v=a6mjt8tWUws&t=32s

Thanks.

**Comment by enesbcs** [comment]
https://github.com/gcgarner/IOTstack/issues/26

**Comment by gcgarner** [comment]
Is there an easy way to run RPIEasy in the background or on startup?

I tried:
`sudo RPIEasy.py &` and it still outputs to the terminal. Should i add a `> /dev/null` redirect?

When running this native is there any easy way to change the default port? 8080 is quite popular

**Comment by enesbcs** [comment]
Yes there are a super easy way: if it is started by root or sudo, then at the Hardware menu at the webgui there are an option for "RPIEasy autostart at boot" (try to use "screen" if installed). Although you can try with & > /dev/null but "screen" is a better way.

Port is autodetected at startup, (80,8080,8008) which is free it will grab it.

**Comment by happytm** [comment]
I think it is implemented now.

https://github.com/gcgarner/IOTstack/issues/26#issuecomment-559644600

Thanks.

**Comment by enesbcs** [comment]
Cool! Did you test it?

**Comment by happytm** [comment]
No. I am away from my PI Zero right now at least for a week . 

Thanks.

**Comment by enesbcs** [comment]
Closed as resolved.
