### ISSUE TITLE
Add Command field in log windows

### ISSUE THREAD

**Issue by tOOmki** [enesbcs/rpieasy#105]
Add command field in the log window.
Now you need to have 2 windows open: log and tools.

**Comment by enesbcs** [comment]
I wouldn't like to change the Log window size if it is not _absolutely_ necessary. By the way usually i am using an ssh terminal to see the logs, but opening two browser tab also not a big deal.

I have rather added the last 5 lines from Log to the "Command Output" window, i hope it will be enough.

**Comment by enesbcs** [comment]
no further feedbacks, issue closed.
