### ISSUE TITLE
Congratulations on First anniversary of RPIEasy

### ISSUE THREAD

**Issue by happytm** [enesbcs/rpieasy#112]
I just realized that first anniversary of RPIEasy is coming up soon. You were able to cover lot of ground in 1 year. In fact most everything required for home automation is already implemented in RPIEasy.

Thank you for your hard work to single handily make it happen.

**Comment by enesbcs** [comment]
Thank you! This year has passed quickly. I still have a few ideas to implement such as the serial GPS modul, e-Paper display support through SPI, Orange Pi GPIO support, USB to GPIO FTDI chip support for PC... just some free time needed. :)
