### ISSUE TITLE
Tools Load fails to open a renamed data file

### ISSUE THREAD

**Issue by alan-rpi** [enesbcs/rpieasy#123]
Under Tools / Save saved file to Windows 7 PC as data..zip  Renamed to RPIEasy Trial data 2020-02-17.zip. Later Tools / Load and browsed to file, selected and then Upload. Get error message:
unzip:  cannot find or open data/RPIEasy, data/RPIEasy.zip or data/RPIEasy.ZIP.
Renamed file back to data.zip and it Uploads OK

**Comment by enesbcs** [comment]
Please avoid using space in filenames, device names and variables.

**Comment by enesbcs** [comment]
If space detected in filenames, error message thrown and upload denied. Resolved in commit https://github.com/enesbcs/rpieasy/commit/3d864a337f610590ff87b5b7dc70805f95ee74f8
