### ISSUE TITLE
Enhancement Request: When closing Device / Task / Edit to return to previous Task List

### ISSUE THREAD

**Issue by alan-rpi** [enesbcs/rpieasy#125]
If one is editing a Device with Task > 16 (e.g. on the page for tasks 16 to 32, say Task 20), then when clicking Close the screen returns to the page for Devices Tasks 1 to 16  not to the page for 17 to 32.

**Comment by enesbcs** [comment]
Fixed in commit https://github.com/enesbcs/rpieasy/commit/3d864a337f610590ff87b5b7dc70805f95ee74f8

**Comment by alan-rpi** [comment]
Another quick implementation :) Tested OK
