### ISSUE TITLE
Enhancement Request: Add Test button to Notification Settings

### ISSUE THREAD

**Issue by alan-rpi** [enesbcs/rpieasy#126]
It would be useful to be able to test the Notification Settings when defining a new or amending an existing Notification. E.g. for an Email(SMTP) a Test button would send a email using the settings defined. If the Test fails (due to technical issue, not with say an invalid Receiver address) then display the error message.

**Comment by enesbcs** [comment]
Test button added at commit https://github.com/enesbcs/rpieasy/commit/3d864a337f610590ff87b5b7dc70805f95ee74f8 Result can be seen in logs.

**Comment by alan-rpi** [comment]
Many thanks for a quick response. Confirmed working :)
