### ISSUE TITLE
Adding OS update possibility

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#136]

**Comment by enesbcs** [comment]
Experimental support for OS update added at commit https://github.com/enesbcs/rpieasy/commit/fb77b90db117bccb7c18a9b2423b1a9265045b61

**Comment by enesbcs** [comment]
Warning: actual Python library installer 'pip3' requires Python3.5! (For older systems, for example Jessie with python3.4 the latest usable pip is v19.1.1) You can install it manually if you wish.

`sudo pip3 install pip==19.1.1`

**Comment by angelo1967** [comment]
Hi Alex,
i tested, all ok
for is very good.

Buona Pasqua
Angelo

Il giorno ven 10 apr 2020 alle ore 20:19 Alexander Nagy <
notifications@github.com> ha scritto:

**Comment by enesbcs** [comment]
Closed as implemented.
