### ISSUE TITLE
miflora read failed = sent 0 temperature

### ISSUE THREAD

**Issue by rrraf** [enesbcs/rpieasy#141]
hi,
i'm having issues with miflora sensors : i'm receiving temperatures at 0°C whenever an error happens in the reading (and it's quite often, i can't manage to have a good bluetooth reception) 👍

14:57:43 MiFlora error: Miflora read failed
14:57:43 Event: MiFlowerBAR#Temperature=0.0

the value 0 is unfortunately sent to the controller (domoticz in my case). i'm also receiving a lot of 0 battery data (there are all full).

regards,
raf

**Comment by enesbcs** [comment]
i can modify this to do not report on error. but how can you find out if the device failed?

**Comment by enesbcs** [comment]
Issue fixed at commit https://github.com/enesbcs/rpieasy/commit/4d2d1eeae4dd74214f7ef1050f9a3834dda4c7e9

**Comment by enesbcs** [comment]
Closed as no feedback.
