### ISSUE TITLE
_P513 BLE Adapter select is missing

### ISSUE THREAD

**Issue by michapr** [enesbcs/rpieasy#145]
In module is no selection for Adapter - and (in my case) the device will not be polled more.

I have tried to add it in code, but it seems something is missing - can you please add it?

Thanks!
Michael

**Comment by enesbcs** [comment]
Not possible. There are no such feature for lywsd02 as Adapter selection.
As i wrote one month ago:

> Also P512,P515,P517,P518 can be modified to support dongle selection.
> P513 and P516 is hardwired to first dongle in their library.
https://github.com/enesbcs/rpieasy/issues/138

You can read about Lywsd02 python module here:
https://github.com/h4/lywsd02

**Comment by enesbcs** [comment]
Looks like that Lywsd02() class parameter name changed, and BLEHelper creation needed before connect section. Fixed at https://github.com/enesbcs/rpieasy/commit/3a51188bb6196a592d8ca6fb9de36e228bddb99c

**Comment by michapr** [comment]
Great, it is working again!
(I wanted to test with external dongle because of possible connection issues, that's why have seen it. But problem was the lib... ;) )

Have seen another typo in _P518 lib (was not working too):
`    ch = self.BLEPeripheral.getCharacteristics(uuid=self.CGG_DATA)[0]`
should be:
`    ch = self.BLEPeripheral.getCharacteristics(uuid=CGG_DATA)[0]`

Thanks!
Michael

**Comment by enesbcs** [comment]
Indeed CGG_DATA is outside of the class. :) Will be added in the next commit!

**Comment by enesbcs** [comment]
P518 fixed at commit https://github.com/enesbcs/rpieasy/commit/625ed596d45d3f0bccf45a4d221b66e58c3b85f5
