### ISSUE TITLE
_P515 MiFlora disabled

### ISSUE THREAD

**Issue by michapr** [enesbcs/rpieasy#147]
Hi,

something is happen with MiFlora plugin.
Since some time the device will be disabled (enable flag removed) by software - and device is not reporting more. This happen as sample after editing other BLE device, but not only then. 

Any idea?

**Comment by enesbcs** [comment]
Yes. Miflora disables itself after 5 unsuccesful read. It can happen if the device is not available or when the 2.4Ghz that is used by both Wifi and BLE devices is very crowded.

**Comment by enesbcs** [comment]
limit raised to 10 in commit https://github.com/enesbcs/rpieasy/commit/625ed596d45d3f0bccf45a4d221b66e58c3b85f5

**Comment by michapr** [comment]
Thanks!
It is stable now for me.
