### ISSUE TITLE
Changing Input - Switch Device/Generic GPIO tigger takes effect only after restart

### ISSUE THREAD

**Issue by matriedel** [enesbcs/rpieasy#154]
Changing Input - Switch Device/Generic GPIO (Push button active low) with edge trigger sending events to MySQL DB Data Storage controller takes only full effect only after a rpieasy restart.

**Comment by enesbcs** [comment]
Yes. When you press "Submit" after changing plugin settings, it calls webform_save(). 
Event detection registering done in plugin_init() which fires at plugin creation and rpieasy startup. Maybe a a self.plugin_init() at the end of webform_save() will solve this.

**Comment by enesbcs** [comment]
Possible fix added at commit https://github.com/enesbcs/rpieasy/commit/303f25e70ff8fbf602329bc34553a262dd2b3d5f

**Comment by enesbcs** [comment]
Closed as no further informations.
