### ISSUE TITLE
usage BLE temp/hum sensor MHO-C401

### ISSUE THREAD

**Issue by michapr** [enesbcs/rpieasy#163]
Hi,
We can use the LYWSD03MMC plugin for MHO-C401. it is compatible.

It is a nice sensor (paper ink) for low price.
https://de.aliexpress.com/i/4001174769598.html

Michael

**Comment by enesbcs** [comment]
Thank you for this information this sensor looks nice! Do you have any information about expected battery lifetime or BLE range?

**Comment by michapr** [comment]
About battery life time in this time not...
BLE range is the same about as LYWSD03MMC, no problem if it is at other floor (!!) if using Raspberry,
both devices have then about -88dBm
