### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by haraldtux** [enesbcs/rpieasy#17]
is it possible to get the uptime set to 1 ?

file : commands.py
line : 453~454
   elif svname==SysVars[13]: #%uptime% 	3244 	Uptime in minutes
    return str(rpieTime.getuptime(0))
to
   elif svname==SysVars[13]: #%uptime% 	0 days 17 hours 27 minutes Uptime in day/houres/minutes
    return str(rpieTime.getuptime(1))

or an additional option that you can choose, or minutes or day/houres/minutes

that reads somewhat easier, for example, on a Oled of dashboard.esp file

thank you, 
greeting Harald

**Comment by enesbcs** [comment]
After commit https://github.com/enesbcs/rpieasy/commit/e69ac666ade2dd86cb9e9833f7d568b39491b3a4
`%c_m2dhm%(%uptime%)`
can be used.

**Comment by haraldtux** [comment]
Thank you :+1:

**Comment by enesbcs** [comment]
No problem.
