### ISSUE TITLE
Pulse counter

### ISSUE THREAD

**Issue by curgan78** [enesbcs/rpieasy#182]
Szevasz!

Áramlásmérőt építettem a fűtésvisszatérőbe. Pulse Counter-rel olvasom ki, de nem találok formula megadási lehetőséget. Az álamlásmérő specifikációja szerint Q*6-8=számolt érték, ahol Q=L/min ESPeasyben benne van, de itt nem találok ilyen lehetőséget.

Köszi
Gábor

**Comment by enesbcs** [comment]
Hm, jogos, a formulaoption paraméter kimaradt a pluginból valamiért és eddig nem hiányzott senkinek. :)
Pótolva. Elképzelhető, hogy újra létre kell hozni a taszkot, hogy megjelenjen.

**Comment by curgan78** [comment]
Nagyon köszi agyors reagálást!


Köszönettel:

 Gábor


Alexander Nagy <notifications@github.com> ezt írta (időpont: 2020. nov. 7.,
Szo, 16:32):

**Comment by enesbcs** [comment]
Issue solved
