### ISSUE TITLE
_P029_DomoOutput  invert logic

### ISSUE THREAD

**Issue by Epik77** [enesbcs/rpieasy#197]
Hi,
I have to connect a 2 channel 5 volt relay on my rpi
I'm using the Output - Output Helper plugin by connecting MQTT to domoticz.
I need to reverse the logic of the gpio port, can you put a flags in the plugins?

thank's :-)

**Comment by enesbcs** [comment]
Its a bit more complicated than just adding a flag, but possible. RPIEasy handles a bit differently the gpio and OutputHelper, if you tried them earlier, you may have observed that if you change the GPIO with "gpio,pin,value" command directly, the OutputHelper value stays in sync with the real value of its assigned pin. (As gpio command checks if the pin is included in an OutputHelper task and changes its value directly.)

**Comment by enesbcs** [comment]
Added at commit https://github.com/enesbcs/rpieasy/commit/b33a111a65f4e138c6ee88b1672e87147e397fde

**Comment by Epik77** [comment]
yes I understand if there are no other solutions I will have to act at the hardware level
https://docs.google.com/file/d/0B5-HND9HJkXWSTQtYlFTZ3VyODA/edit 

do you have any workaraounds to offer me?

**Comment by Epik77** [comment]
Sorry,

after Added at commit b33a111

this device works correctly

thank you :-)

**Comment by enesbcs** [comment]
Closed as implemented
