### ISSUE TITLE
P502_PyGameSnd disable loop

### ISSUE THREAD

**Issue by Epik77** [enesbcs/rpieasy#208]
Hi,
I need to run preset voice commands the plugins in question would be fine but they run continuously ...
Is it possible to disable the loop or are there any other plugins that I can integrate for this purpose?
Thanks for the support

**Comment by enesbcs** [comment]
P503 plugin play sounds once.
But i can add a parameter to specifiy loop count to P502 if it is necessary for your use case.

I am using P502 for continous alarms, and P503 for single welcome sound currently.

**Comment by Epik77** [comment]
Yes thanks,
you solve a big problem for me,
I have to upload several mp3s and I would go to occupy many tasks 
thanks :-)

**Comment by enesbcs** [comment]
Enhancement: add Loop count parameter to P502

**Comment by enesbcs** [comment]
Support added at commit https://github.com/enesbcs/rpieasy/commit/07ae76219f4e73f2b55a48bcf14fb084f7d6953a

**Comment by Epik77** [comment]
thank you very much
it works properly :-)
