### ISSUE TITLE
Feature Request: Assign a GPIO to the RunOS command

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/rpieasy#209]
As the title says I'm wondering if inside the plugin a setting for a GPIO pin to toggle the command could be implemented. This would reduce or eliminate the need for rules to toggle the command.

Thoughts?

**Comment by enesbcs** [comment]
Interesting. You are planning to run linux console commands with GPIO connected button presses?

**Comment by Budman1758** [comment]
> You are planning to run linux console commands with GPIO connected button presses

Actually it will be kind of automatic. My truck computer will have a dash cam that will record most of the time. Controlled by gpio connected to a box that outputs what gear the truck is in. Put truck in drive, camera records. Put in park, recording stops. Along those lines.

**Comment by enesbcs** [comment]
i guess i can add some option like "Input trigger condition" and a GPIO selector. However it will add GPIO as a dependency to use this plugin which is not the best choice.

How about referring to another Task (any task by its name, can be a P001) from the RunOs task, and reacting this trigger task  values?

**Comment by Budman1758** [comment]
> However it will add GPIO as a dependency to use this plugin which is not the best choice.

Maybe the GPIO can be optional in the plugin then GPIO would only be necessary if wanted.

**Comment by enesbcs** [comment]
> > However it will add GPIO as a dependency to use this plugin which is not the best choice.
> 
> Maybe the GPIO can be optional in the plugin then GPIO would only be necessary if wanted.

"Optional" term is unknown yet in the RPIEasy dependency system. May need a complete rewrite.

**Comment by Budman1758** [comment]
> May need a complete rewrite.

Like I said earlier, this is not a big deal. I would not go too far out of the way on this.....

**Comment by enesbcs** [comment]
I will find a way to add this feature. :)

**Comment by enesbcs** [comment]
Added Trigger Value support at commit https://github.com/enesbcs/rpieasy/commit/eb09739e59bfbd59b97aec83cc6fb2c50c28216e
It will check the linked Task 10 times a second if it's state is changed, and executes the proper command.

**Comment by Budman1758** [comment]
That seems to work pretty well. Thanks!!

**Comment by enesbcs** [comment]
Closed as implemented
