### ISSUE TITLE
P019: add option to report status to the controller even if type is output

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#215]

**Comment by clumsy-stefan** [comment]
Just for testing I added the following statement to P019 after line 92 (before `try:`. This seems to work for my setup, but can't say what happens to MQTT obviously.
```
     self.timer100ms = True
     misc.addLog(rpieGlobals.LOG_LEVEL_DEBUG,"PCF 1/10s timer enabled with update")
```

**Comment by enesbcs** [comment]
> Just for testing I added the following statement to P019 after line 92 (before `try:`. This seems to work for my setup, but can't say what happens to MQTT obviously.
> 
> ```
>      self.timer100ms = True
>      misc.addLog(rpieGlobals.LOG_LEVEL_DEBUG,"PCF 1/10s timer enabled with update")
> ```

May work, as handler will only send data if actual state is not equal to the last reported state. (but may add extra cpu usage of course as if you are not using interrupt callbacks, polling requires more resource everytime)
I can add an option to activate 1/10s timer manually to the plugin settings.

**Comment by clumsy-stefan** [comment]
Yes an option sure would be nice. If I'm not wrong, I added the counter where the check for interrupt callback is false (and only then).

**Comment by enesbcs** [comment]
Found a typo in the plugin, i think that this workaround is not necessary anymore. 
https://github.com/enesbcs/rpieasy/commit/fadb8031612dd6efbce9efdd9c9f97999a9e8514

**Comment by clumsy-stefan** [comment]
Seems to be working (without my workaround) now! Thanks a lot!

**Comment by enesbcs** [comment]
Thanks for testing, closing for now!
