### ISSUE TITLE
[Cosmetics] Clock is only updated on the first task page.

### ISSUE THREAD

**Issue by clumsy-stefan** [enesbcs/rpieasy#220]
When switching to other task/device pages with `>` the clock at the bottom left is not updated/set anymore (only on the first page it seems to work).

![image](https://user-images.githubusercontent.com/32835100/110250930-585c8f80-7f7e-11eb-909b-1245992fc8ba.png)

Nice to have, but not really an issue ;)

**Comment by enesbcs** [comment]
javascript magic :D

**Comment by clumsy-stefan** [comment]
It also doesn't work on a page full of tasks (if you mean this by "variables"):

![image](https://user-images.githubusercontent.com/32835100/110253984-577f2a00-7f8d-11eb-8d57-3e35e1e8afd5.png)

**Comment by enesbcs** [comment]
Clock update altered in commit https://github.com/enesbcs/rpieasy/commit/9946ccc9294222c847f5005e2b38a4c66a2bfa64

**Comment by clumsy-stefan** [comment]
Working on all pages now for me! Issue can be closed IMHO, thanks a lot!

**Comment by enesbcs** [comment]
Closed as solved.
