### ISSUE TITLE
[Feature] Add support for MCP3424

### ISSUE THREAD

**Issue by clumsy-stefan** [enesbcs/rpieasy#224]
While migrating a node from ESPEasy to RPIEasy I realized that the ADC MCP342x is not yet supportet. If that could be integrated in a future realase it would be great!

**Comment by clumsy-stefan** [comment]
I'd be happy to send you one of these,, but I guess the shipping is more expensive than ordering directly...

There is a python module that implements a class for these series of ADC, probably this could be reused?
[https://github.com/stevemarple/python-MCP342x](MCP342x)

If this could be integrated in RPIEasy I could do tests and adapt the module, as currently I have no clue how to "correctly" integrate such a module in RPIEasy, sorry...

**Comment by enesbcs** [comment]
Yes, this python library seems ok.
https://pypi.org/project/MCP342x/

I would start by reusing P025 to add MCP342x. For multitask usage a "router" library is also needs to be created which holds real device entity, plugin dependency page also needs to be adjusted, etc..

**Comment by clumsy-stefan** [comment]
I had a quick look at P210 (MCP3008) as a start point, but honestly I currently refrain a bit from learning another programming language ;) adn finding out how RPIEasy is structured... Took me quite some time when I startet with ESPEasy... But who knows, if I get bored, maybe it would be an interesting challenge ;)

**Comment by enesbcs** [comment]
MCP3008 is an SPI based device, but MCP3423 and ADS1015 is I2C connected. I've ordered a cheap MCP3424 from Aliexpress without tracking, it will arrive to me in two month.. i hope.

**Comment by clumsy-stefan** [comment]
Just wanted to ask if you had any luck with shipping or if it's probably also stuck on the Evergiven (as some of my stuff seems to be ;) ?

**Comment by enesbcs** [comment]
its eventually arrived after 90 days, but currently i am working on other projects, and i can not say a date for this plugin.

**Comment by enesbcs** [comment]
Not yet, but it will be the next in the line!

**Comment by enesbcs** [comment]
Either my device is faulty, or the library works very oddly... measuring 1.5v seems ok, but measuring a 3v battery shows 2v...
On the other hand if the library is working it needs to be rewritten to support multitasking environment.

**Comment by clumsy-stefan** [comment]
thanks for the update, this doesn't sound very encouraging... Probably there is another library that can be used?

**Comment by enesbcs** [comment]
I've found another https://github.com/kleebaum/bayeosraspberrypi/blob/master/bayeosraspberrypi/mcp3424.py but i read MCP3424 datasheet in the meantime which states that +/- 2.048V is the input data range, so i guess it is working as it should. But i've never used such thing before i prefer ADS1015 which works upto 3.3V input...

**Comment by enesbcs** [comment]
Added support at https://github.com/enesbcs/rpieasy/commit/a51d0fb8a6b74141f1786c8d755905fbc3e6ad18

**Comment by clumsy-stefan** [comment]
Great! Thanks... I'll test it asap (probably next weekend ) and give feedback...

**Comment by clumsy-stefan** [comment]
Installed new version and tried with my MCP3424 which seem to work flawless!!

Again, thanks a lot for implementing this. I can now retire one more old installation and move everything to RPIEasy!!

**Comment by enesbcs** [comment]
Thanks for testing, it was the longest "work-in-progress" state plugin since RPIEasy created.
