### ISSUE TITLE
Ili9341

### ISSUE THREAD

**Issue by cybermandiant** [enesbcs/rpieasy#235]
Hi I will want to test with a tft ili9341 2.4 i have activ spi in my rpi and on rpieasy I can not find how to connect it someone can tell me what the enable pin is because I do not have one on my screen I have dc miso mosi sck cs led vcc gnd reset Thank you

**Comment by tonhuisman** [comment]
`Enable` -> `cs` (read: 'chip select')

For a clear view you will have to connect `led` to `vcc`, I expect, as led is usually the backlight.

**Comment by cybermandiant** [comment]
Thanks for your fast reply i have try this... Not work i have connect bl directly to 3.3v

**Comment by cybermandiant** [comment]
Yes led is my backlight

**Comment by cybermandiant** [comment]
Is work perfectly in esp32 not work with my rpi zero w

**Comment by cybermandiant** [comment]
Yes is working i have reset all my raspberry

**Comment by cybermandiant** [comment]
Thanks a lot for all :)
