### ISSUE TITLE
Interesting machine learning project.

### ISSUE THREAD

**Issue by happytm** [enesbcs/rpieasy#236]
Not an issue.

Just FYI.   https://www.youtube.com/watch?v=p5QJj1aCjnQ

Thanks.

**Comment by enesbcs** [comment]
As i see its a json wrapper on top of pocketsphinx. Interesting, it may even usable with working wakeword support.

**Comment by enesbcs** [comment]
PocketSphinx plugin available as P506 plugin in RPIEasy, however voice2json has no python bindings, so its not really friendly to RPIEasy.
