### ISSUE TITLE
OpenTherm support?

### ISSUE THREAD

**Issue by vampywiz17** [enesbcs/rpieasy#243]
Hello there,

It possible to add OpenTherm support, like ESPeasy do this?

https://github.com/okar1/ESPEasy-OpenTherm

https://github.com/ihormelnyk/opentherm_library

**Comment by enesbcs** [comment]
I guess it is possible to add, if anyone has an opentherm device and a lots of free time.
Unfortunately I do not have any of the above.

**Comment by vampywiz17** [comment]
I have this device and I able to help you.

**Comment by enesbcs** [comment]
a device which clones me would help a lot :D

**Comment by vampywiz17** [comment]
> a device which clones me would help a lot :D

I understand you :)

**Comment by TD-er** [comment]
> a device which clones me would help a lot :D

If you have found one, I want one too!

**Comment by Budman1758** [comment]
> a device which clones me would help a lot :D

Count me in on that. Perhaps a younger version would be nice also.....

**Comment by Yocee84** [comment]
This not help?
https://github.com/okar1/ESPEasy-OpenTherm

**Comment by enesbcs** [comment]
Closed as stalled
