### ISSUE TITLE
Telegram notifications - chat-id

### ISSUE THREAD

**Issue by haraldtux** [enesbcs/rpieasy#244]
Hello,

Is it possible to make a box (input window) for the "chat-id" in Telegram notifications?
Chat ID you need to send it to Telegram.
I Can enter it in the (data) notifiers.json file, but it would be handy if it could be done via the web gui.
Furthermore, the Telegram notifications work well with input of the chat id.

greeting Harald

**Comment by enesbcs** [comment]
I see. Although chat-id has to be created on first run automatically.
Chat-id box added to plugin at commit https://github.com/enesbcs/rpieasy/commit/fadb8031612dd6efbce9efdd9c9f97999a9e8514

**Comment by haraldtux** [comment]
functions perfectly, 

thank you
