### ISSUE TITLE
Shelly mqtt domoticz problem

### ISSUE THREAD

**Issue by offsaid** [enesbcs/rpieasy#246]
hi! Domoticz log shows me a message: --> New hardware creation disabled! <--  Shelly: (Shelly) Connected to MQTT Server: ....... and when I add a new shelly device: shelly Status: Shelly: (Shelly) Error adding device..... Pls help

**Comment by enesbcs** [comment]
Try to enable new hardware creation in Domoticz settings... If global New hardware creation is false, than this error message will appear.

**Comment by offsaid** [comment]
OMG. it works :) THX!
