### ISSUE TITLE
no longer updates

### ISSUE THREAD

**Issue by docsparks** [enesbcs/rpieasy#247]
having been on this version for months to my understanding, git updates always says update failed

> Build | RPIEasy 2.1.234
> Libraries | Python 3.7.3 (default, Jan 22 2021, 20:04:44)[GCC 8.3.0] Linux-5.10.52+-armv6l-with-debian-10.10
> OS: | linux 5.10.52+
> OS full name: | Raspbian GNU/Linux 10 (buster)

**Comment by enesbcs** [comment]
Indeed 2.1.234 is the latest currently. There are some open issues, which needs to be dealed sometime, however i have not got so much free time nowadays.

If git pull command failing there could be several problems on the client side: date/time mismatch, openssl related problem, old git client application, not enough free space, other regular linux system problems. :)
