### ISSUE TITLE
p2p port

### ISSUE THREAD

**Issue by uzi18** [enesbcs/rpieasy#253]
https://github.com/enesbcs/rpieasy/blob/6899231bf86ab23e6554335e636b892d9f35b08f/_C013_ESPEasyP2P.py#L35

default port should be 8266

**Comment by enesbcs** [comment]
Ok, changed at commit https://github.com/enesbcs/rpieasy/commit/5a2f7729ea0fb9ef6bf313f64ebf5c475c1e4730

**Comment by uzi18** [comment]
This was a fault in Espeasy p2p controller code and also will be fixed - PR pending. 
Thanks
