### ISSUE TITLE
Lechacal / RPICT3T1

### ISSUE THREAD

**Issue by cod-xio** [enesbcs/rpieasy#261]
Hello, has anyone already used an Energy Meter from Lechacal / RPICT3T1 with RPIEasy or does anyone have an idea?

**Comment by enesbcs** [comment]
This hat has an Attiny which sends data through serial in this format:
NodeID P1 P2 P3 Temperature

A new plugin has to be written for example based on the similar serial based P053:
https://github.com/enesbcs/rpieasy/blob/master/_P053_PMSx003.py
to read values into RPIEasy.

**Comment by cod-xio** [comment]
Well, super, I'm unfortunately overwhelmed here, so I'll probably continue sending it to Influx with lcl-gateway_2.0.0!
