### ISSUE TITLE
Feature Request. I2C rotary encoder support.

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/rpieasy#262]
I stumbled into these at Adafruit the other day and methinks it would be pretty awesome if these could have support. Would make for much simpler setups. Also ability to support many of them over only 2 GPIO.

https://www.adafruit.com/product/4991

**Comment by enesbcs** [comment]
It has python example, but as all of it relying on adafruit own libraries it has to be rewritten completely to be used in RPIEasy.
Every rotary has an unique Attiny device integrated on it and all of them needs special cabling? Interesting approach.

**Comment by Budman1758** [comment]
Pretty sure the cabling is just standard I2C, power and ground. They use that on a lot of their stuff.

**Comment by enesbcs** [comment]
Yep with a non-standard connector

**Comment by Budman1758** [comment]
@enesbcs  Would you like me to send you a device and a wiring connector? I have some on the way. Let me know.

**Comment by enesbcs** [comment]
@Budman1758 Actually 3GPIO needed, as INT pin is mandatory, but yes 8 I2C rotary encoder could be added. Works pretty fast, although i have tested it only one rotary.
Support added at commit https://github.com/enesbcs/rpieasy/commit/1bbca1375f90db5f690510040d5d86f896ac1d78

**Comment by enesbcs** [comment]
Also find a cheaper i2c rotary, which is not made by Adafruit, ordered one of them also for testing:
https://www.duppa.net/shop/i2c-encoder-mini/?v=35b5282113b8

**Comment by enesbcs** [comment]
Closed as implemented
