### ISSUE TITLE
rules syntax or me failed?

### ISSUE THREAD

**Issue by introisback** [enesbcs/rpieasy#265]
can someone tell me how my rules doesn´t work?

on System#Boot do
  LoopTimerSet,1,2
endon

on Rules#Timer=1 do
 if [Oelkessel#C]=>49.0 and [Boiler#C]<=49.0 
   GPIO,24,1
   timerSet,2,900 
 elseif [PufferspO#C]>49.0
   GPIO,24,1
   GPIO,23,1
   timerSet,3,1200
 else
  gpio,24,0
 endif
endon

with or without [ ] neither works.
even if I try instead of GPIO's - events no function

**Comment by enesbcs** [comment]
Try to use simple if else statements, even nested IF's. I do not remember 'elseif' or several 'else' in one 'if' in the rule syntax in 2019 when it is coded into rpieasy.

**Comment by introisback** [comment]
okay thank you so much,
