### ISSUE TITLE
LYWSD03MMC Xiaomi temperature sensor stuck in Bluetooth communication

### ISSUE THREAD

**Issue by sorinutzu** [enesbcs/rpieasy#268]
Hi,

I am using RPIEasy since a while on RPI-3B+ and RPI Zero W with 10 Xiaomi temperature & humidity sensor LYWSD03MMC on Bluetooth. Everything works fine but since ~one week ago sensors read with RPI-3B+ all remains stuck on communication mode active (Bluetooth icon from upper right being ON) then connection with them is lost, then battery is drained. The RPIEasy from RPI Zero W still working good, no issues, I have moved the sensors on this RPI Zero W and are working fine again. I did not done any change/update/installation on RPI-3B+ before issue begun. I have updated OS and RPIEasy on RPI 3B+ but the same, no fix. 

Versions : 
- RPI-3B+ :  RPIEasy v2.2.212 then updated to v2.3.022, both with issues; "Raspbian GNU/Linux 11 (bullseye)"; python 2 and 3 installed but default is Python 3.9.2
- RPI Zero W : RPIEasy v2.2.168, working fine ; "Raspbian GNU/Linux 10 (buster)"; python 2 and 3 installed but default is Python 2.7.16

Do you know what is the root cause ?  What can I do to fix broken RPIEasy version ? 
I would like to rever from RPIEasy v2.3.022 (latest) to RPIEasy v2.2.168, where can I find an archive of RPIEasy v2.2.168 ?

Thank you !

**Comment by enesbcs** [comment]
Closed as no response
