### ISSUE TITLE
Ina219 possible to add Gain and ADC settings? 

### ISSUE THREAD

**Issue by Micha-123** [enesbcs/rpieasy#272]
is it possible to add settings like,  shunt ohms, (now i have adit it in _P027_INA219.py file 
also wil be fine to have the Gain and ADC funktion.

i use an external shunt 200Amps, 75mΩ (0,075Ω)  and it wil be fine to set it to ADC_128SAMP

in the simple script i have it like 

ina.configure(ina.RANGE_16V, ina.GAIN_2_80MV, ADC_128SAMP)

from this site https://pypi.org/project/pi-ina219/

**Comment by enesbcs** [comment]
Possible if you specify which options in which forms is needed... selector/textbox, possible values, ranges... as i do not use INA219 since it is implemented i have no idea about its parameters.
Although i can find out myself, if there is a plenty of time...

**Comment by Micha-123** [comment]
```
#!/usr/bin/env python
from ina219 import INA219
from ina219 import DeviceRangeError

SHUNT_OHMS = 0.1
MAX_EXPECTED_AMPS = 0.2


def read():
    ina = INA219(SHUNT_OHMS, MAX_EXPECTED_AMPS)
    ina.configure(ina.RANGE_16V, ina.GAIN_2_80MV, ina.ADC_128SAMP)
```

thats my simple script 

SHUNT_OHMS -> Textbox
MAX_EXPECTED_AMPS  -> Textbox


ina.RANGE_16V / ina.Range_32V -> selector of the two possible values 

ina.GAIN_AUTO / ina.GAIN_1_40MV / ina.GAIN_2_80MV / ina.GAIN_4_160MV / ina.GAIN_8_320MV -> selector 5 values

ina.ADC_9BIT / ina.ADC_10BIT / ina.ADC_11BIT / ina.ADC_12BIT / ina.ADC_2SAMP / ina.ADC_4SAMP / ina.ADC_8SAMP / ina.ADC_16SAMP/ ina.ADC_32SAMP / ina.ADC_64SAMP / ina.ADC_128SAMP,  -> Selector with 11 values

**Comment by enesbcs** [comment]
Yep addFormFloatNumberBox() only support input with 2 digits... another input may be needed for values smaller than 0.001. This is the first reason i asked for ranges.

**Comment by enesbcs** [comment]
Dropped forcing number format, changed to free text input at commit https://github.com/enesbcs/rpieasy/commit/b14193308604bad16edb7f5789e6e30ab628b363
