### ISSUE TITLE
measure a 48V battery up to 60V?

### ISSUE THREAD

**Issue by introisback** [enesbcs/rpieasy#273]
Hello team, what is the best way to measure a 48V battery so up to 60V ?
Is there already the possibility to do something like this, or do I have to hope that the INA169 is imported?

Many greetings

**Comment by enesbcs** [comment]
INA169 is an analog sensor.
You can connect any analog sensor to the Raspberry with an ADC module, such as MCP342x, ADS101x, PCF8591, MCP3008. These are supported in RPIEasy.
