### ISSUE TITLE
Failed to get unit file state for rpieasy.service

### ISSUE THREAD

**Issue by Garyxxzx** [enesbcs/rpieasy#276]
I am running rpieasy on a pi 3b+, it was running quite happily however it has stopped running and if I attempt to manually restart I get the error "Failed to get unit file state for rpieasy.service" this occurs whilst starting the web server. 
Any assistance you can give would be greatly appreciated.

**Comment by enesbcs** [comment]
You can use the good old "RPIEasy autostart at boot with rc.local (recommended)" setting instead systemctl method.

**Comment by Garyxxzx** [comment]
added a line to rc.local and it started fine, thank you
