### ISSUE TITLE
!PN532 init error:'Plugin' object has no attribute 'i2cl'

### ISSUE THREAD

**Issue by Pierrick-R** [enesbcs/rpieasy#277]
PN532 module not able to work.
Issue in _P017_PN532.py
line 69 : 
     self.pn = pn532.PN532_I2C(reset=self.preset,i2c_c=self.i2cl)
to be changed by
     self.pn = pn532.PN532_I2C(reset=self.preset,i2c_c=self.i2c)

Tested - it's working now

Pierrick

**Comment by enesbcs** [comment]
Yep, its my bad, thanks for fixing, added to current release!
https://github.com/enesbcs/rpieasy/commit/a7d1219c2e98045c7ac10afb01f529aed55b88b5
