### ISSUE TITLE
 PZEM016/004 -> fast slow?

### ISSUE THREAD

**Issue by introisback** [enesbcs/rpieasy#278]
Hi guys , i need to read my AC power under 10 seconds to shut down my heatcoil.
How fast is fast or slow?

I hope you can help me before i buy 2 and ship 1 back and buy other 2 for my 3 phase AC.

best greetz to hungary and rest of the world
chris

**Comment by enesbcs** [comment]
PZEM016 default setting is "Fast", and it uses 0.1 seconds timeout to Modbus commands.
PZEM004 may give bad results with fast setting, but seems stable with the "Slow" setting, which means 3 seconds timeout to Modbus commands.

PZEM004 may work with 5 seconds interval +/-3 sec, but avoid if you can.

**Comment by introisback** [comment]
thx so much. nice weekend
