### ISSUE TITLE
Unknown command: PZEMRESET,1

### ISSUE THREAD

**Issue by Epik77** [enesbcs/rpieasy#279]
Hi, 
I wanted to reset the counter of my pzem004t but the command is not found.
could you fix it?
Thank you

**Comment by TD-er** [comment]
The command is `resetenergy` and it seems like the parameter should be the modbus address.

**Comment by Epik77** [comment]
same result
11:15:01 : CMD: resetenergy
11:15:01 : Unknown command: resetenergy
or
11:15:51 : CMD: resetenergy,1
11:15:51 : Unknown command: resetenergy,1

**Comment by TD-er** [comment]
I already removed my reply, since I overlooked this was about RpiEasy, not ESPEasy ;)

**Comment by enesbcs** [comment]
# Available commands:
#  PZEMADDRESS,<currentaddress>,<newaddress>   	- change address of pzem device
#  PZEMRESET,<address>			 	- PZEM reset energy at address

if the PZEM device is not initialized in RPIEAsy or, address is unknown or resetenergy() returns False, then the result is unknown command.

**Comment by enesbcs** [comment]
I've added more log output to current release, please upgrade and check console log
https://github.com/enesbcs/rpieasy/commit/a7d1219c2e98045c7ac10afb01f529aed55b88b5

**Comment by Epik77** [comment]
Hi this output:

False
15:39:05 : PZEM004 reset error: 'Instrument' object has no attribute '_performCommand'
15:39:05 : PZEM reset command failed!
15:39:05 : PZEM004 reset error: 'Instrument' object has no attribute '_performCommand'
15:39:05 : PZEM reset command failed!
15:39:05 : Unknown command: pzemreset,1

**Comment by enesbcs** [comment]
> 15:39:05 : PZEM004 reset error: 'Instrument' object has no attribute '_performCommand'

I see... when i wrote the plugin at 2020 there was a "_performCommand" function. And now it is called as "_perform_command".. magnificent. :D
"Note that the API might change, as this is outside the official API."

Could you please change your
"lib/lib_pzem.py" file both occurences of this:

self.dev._performCommand(66,'')

to these:

self.dev._perform_command(66, b'')

**Comment by Epik77** [comment]
Very good
replaced performCommand with perform_command
now the command works correctly:

08:44:52 : Timer 2 started with timeout: 5
08:44:52 : Unit alive: 21
08:44:52 : Unit alive: 13
08:44:54 : CMD: pzemreset,1


![immagine](https://github.com/enesbcs/rpieasy/assets/52275216/4a04b2d5-b47a-41c1-acd1-9955809137e0)


thanks for support :-)

**Comment by enesbcs** [comment]
Thank you for testing, i will add this fix to the next commit!
