### ISSUE TITLE
RPI 4 - Hardware type not shown and unknown GPIO

### ISSUE THREAD

**Issue by harrybzh** [enesbcs/rpieasy#282]
Good evening,

I got a pretty similar issue as gary got here I think :
https://github.com/enesbcs/rpieasy/issues/201#

With this message: "This hardware has unknown GPIO."

As I got this by running cat /proc/cpuinfo :
```

cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03115
Serial          : 100000005bcf396b
Model           : Raspberry Pi 4 Model B Rev 1.5
```

And I can't seem to find c03115 in linux_os.py

Could it be the same issue ?

I have also issues with the autostart with rc.local. It seems the bash script doesn't run properly, but when I call it manually it starts ... any hints on this ?

Thank you

**Comment by tonhuisman** [comment]
@harrybzh What is the memory size of your RPi4, 4GB or 8GB? (Doesn't really matter, except the shown info won't be correct if it's the 8GB model 😋)

**Comment by harrybzh** [comment]
Just modifying linux_os.py with the new one ... did actually work :) thank you for the reactivity !
