### ISSUE TITLE
Working with Rpi Pico (no wifi chip) through USB?

### ISSUE THREAD

**Issue by PizzaProgram** [enesbcs/rpieasy#286]
This project seems to be great, but one thing is not clear reading all these documentation:
 - Is this firmware working with a simple [Raspberry Pi Pico](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) ?  (The one without the Wifi chip, only RP2040 .)
 - So can it somehow simulate MQTT through USB = serial communication?

I'd like to use it with node-red.

**Comment by enesbcs** [comment]
RPIEasy made for computers with Linux Operating System.
Raspberry Pi Pico is a microcontroller. 

The LAN (W5100S-EVB-Pico) and the Wifi (Pico-W) variant will work with mpyeasy-async:
https://github.com/enesbcs/mpyeasy-async

I saw a basic experimental USB RNDIS support to RP2040 in micropython but it never reached the stable edition, so its unlikely that i can add support for that in the near future:
https://github.com/micropython/micropython/commit/f782c8b5a6d6e9f65c2a4feeaaa95a192ab2a123
