### ISSUE TITLE
New plugin: PCF8574 IO Expander.

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/rpieasy#42]
While we are adding plugin requests I thought I'd throw this one into the mix. This is quite similar to the MCP23017 chip but it only has 8 GPIO.  Very popular for a multitude of things. As time permits of course. :)

**Comment by enesbcs** [comment]
Maybe i have a PCF8574 somewhere, but i never used before. I have to search it. :)

**Comment by enesbcs** [comment]
I was wrong, i have only a PCF8591. So i ordered a PCF8574 now.

**Comment by enesbcs** [comment]
Support added in commit https://github.com/enesbcs/rpieasy/commit/df05d2d09f10ef1edb76af8e204e3f93b7a2c912
