### ISSUE TITLE
New plugin: VL53L0X distance meter

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#44]
Library for implementation: (preliminary testing needed)
https://pypi.org/project/VL53L0X/

**Comment by enesbcs** [comment]
Back to square 1, pip3 install VL53L0X output: "No matching distribution found for VL53L0X"

**Comment by Budman1758** [comment]
I just downloaded the files from the link in your first post.  Maybe they are just not in the python package index for some reason.

**Comment by enesbcs** [comment]
Maybe, but if it's not in the index than it would not be so easy to write a dependency check and autoinstaller for it. In the meantime i've found an other python sample, which may be more useful, but needs some rewriting.
https://github.com/DexterInd/DI_Sensors/blob/master/Python/di_sensors/VL53L0X.py

**Comment by enesbcs** [comment]
Test version added in commit https://github.com/enesbcs/rpieasy/commit/44392baeb54be6da2822bcc8b3d8f3a06ee1ab9e

**Comment by enesbcs** [comment]
Implementation issue is closed now.
