### ISSUE TITLE
Neopixel feedback

### ISSUE THREAD

**Issue by haraldtux** [enesbcs/rpieasy#48]
was here with NeoPixel and Rules to been playing around, works very well :+1: 
my test/example Rules : 

on DS18b20#Temperature do
  if [DS18b20#Temperature]>21
     NeoPixelAll,255,0,0,10 ##Red
  endif
  if [DS18b20#Temperature]<=21
     NeoPixelAll,255,0,255,10 ##Purple
  endif
  if [DS18b20#Temperature]<=20
     NeoPixelAll,255,255,0,10 ##Yellow
  endif
  if [DS18b20#Temperature]<=19
     NeoPixelAll,0,255,0,10 ##Green
  endif 
  if [DS18b20#Temperature]<=18
     NeoPixelAll,0,0,255,10 ##Blue
  endif   
endon

**Comment by enesbcs** [comment]
Thank you for your feedback, this issue is closing now. Please feel free to open a new issue, in case of an error related to neopixel plugin.
