### ISSUE TITLE
New plugin: SR04 range finder

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#49]

**Comment by TD-er** [comment]
Please note that some of these need some extra electronics like a level converter.
Or else you may damage GPIO pins.
And for the Arduino environment we use the "newping" library, which appeared to be way more stable compared to the previous implementation.

**Comment by enesbcs** [comment]
I know, already used an SR04 with ESPEasy for presence detection in restroom, with a voltage divider. (2 resistor)
For Linux/Python the newping library is not an option, and i think a multitasking Linux OS will not provide as accurate timings as an ESP8266/Arduino hardware. Despite that my first test results seems fine in pure python. Now i will test it with multithreading code.

**Comment by enesbcs** [comment]
Support added in commit https://github.com/enesbcs/rpieasy/commit/3d697ce638291ab25d29b3e42e70f0875f95fa77. Seems to works ok in multithreaded environment. I have experienced 1-4mm differences between measures with physically same distances. There were some big values in multiple measures, but with 5-8 samples at once the plugin can filter them - mostly.

**Comment by enesbcs** [comment]
Implementation issue is closed now.
