### ISSUE TITLE
New plugin: Liquidcrystal i2c LCD

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#51]

**Comment by haraldtux** [comment]
you were just for me Alexander , just wanted to open these issues
2x16 and 4x20 LCD

Maybe you can use this lib, works well on a Raspberry
https://github.com/dbrgn/RPLCD

**Comment by enesbcs** [comment]
RPLCD looks fine as it available on th pypi, but needs further testing.

**Comment by enesbcs** [comment]
Added in commit https://github.com/enesbcs/rpieasy/commit/72fabc9b77adbeee1b5ef9b272c3e16232fcdacd

**Comment by haraldtux** [comment]
first test (with me) LCD 2x16 as 4x20 works well :+1: 

Thank you so much

**Comment by enesbcs** [comment]
Thank you for your feedback, implementation case is now solved.
