### ISSUE TITLE
RPiEasy "build" variables for display on a LCD ?

### ISSUE THREAD

**Issue by haraldtux** [enesbcs/rpieasy#52]
is there a possibility or is there an option to RPiEasy "version" (build) variables for display on a LCD, Oled or deskdord.esp ?

**Comment by enesbcs** [comment]
I've added %build% global variable in commit https://github.com/enesbcs/rpieasy/commit/24d0dd1f6a2de085bb356f6152c51730d8205b89 if this is enough.

**Comment by haraldtux** [comment]
works !!
yes this is enough
can be closed
thank you

**Comment by enesbcs** [comment]
Thanks, issue closed now!
