### ISSUE TITLE
Main pages icons

### ISSUE THREAD

**Issue by haraldtux** [enesbcs/rpieasy#59]
Hello Alexander and RPiEasy users,
was been at the arts and crafts, maybe you find it nice icons in the main pages

![main-icoon](https://user-images.githubusercontent.com/39169481/56492909-82714980-64ed-11e9-987a-d364d9042e71.png)

file : rpieGlobals.py
code (line 14~22): 
`gpMenu = []`
`gpMenu.append(['\u2302 Main','.'])`
`gpMenu.append(['\u2699 Config','config'])`
`gpMenu.append(['\U0001f4ac Controllers','controllers'])`
`gpMenu.append(['\U0001f4cc Hardware','hardware'])`
`gpMenu.append(['\U0001f50c Devices','devices'])`
`gpMenu.append(['\u29f4 Rules','rules'])`
`gpMenu.append(['\u2709 Notifications','notifications'])`
`gpMenu.append(['\U0001f527 Tools','tools'])`

Icon list : https://www.charbase.com/block/miscellaneous-symbols-and-pictographs

btw:
with Linux Debian Chromium Web Browser not all icons are displayed (emember that I have a somewhat older Debian ver. turn)
with Windows 10 Chrome Web Browse It is good

**Comment by TD-er** [comment]
These are the icons used currently in ESPeasy, and those were chosen because we simply needed some icons for the view of tabs in the small view of mobiles.
By using those icons, you simply don't need to have images embedded in the firmware, which saves space.

I guess that if you find better ones to be used in RpiEasy, we should also use them in ESPeasy.

**Comment by enesbcs** [comment]
In fact in RPIEasy any png images can be added to the html as there are a lot of memory and SD card place available.. but i really like this minimalistic approach. :) Thanks for contributing, added with todays commit to RPIEasy!

**Comment by enesbcs** [comment]
Generally i think that the current icons is fine. Altough i can imagine these
- for Rules https://www.charbase.com/1d11a-unicode-musical-symbol-five-line-staff
- for Hardware: https://www.charbase.com/2328-unicode-keyboard
Maybe it would be a good idea to put a vote/survey on this in the letscontrolit forum?

**Comment by haraldtux** [comment]
nice, It works !!

Thank you

**Comment by enesbcs** [comment]
Issue closed as no other feedbacks provided. Feel free to reopen in case of related ideas.
