### ISSUE TITLE
Add AP mode

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#6]
Create an AP when wifi connection unavailable for headless configuration

**Comment by ironataerail** [comment]
Would be nice having an AP mode option, to run rules as a standalone device on locations w/o inet connectivity.

**Comment by enesbcs** [comment]
After long trying a method is implemented to enter AP mode if connection failed for some reason. It depends on hostapd  & dnsmasq packages, for my RPI Zero W + Raspbian, it is working, but prepare yourself with a backup solution if you enable this feature and something go bad!
