### ISSUE TITLE
Feature request: Implementation of LWT

### ISSUE THREAD

**Issue by bennybubble** [enesbcs/rpieasy#69]
Hi,

Would it be possible to implement LWT like in ESPEasy ?

-ben

**Comment by enesbcs** [comment]
It can be, however i've never used this feature.
I guess the controller plugin needs 3 parameters:
1: lwl topic
2: lwl connect message (unit sending it automatically to lwl topic when connected?)
3: lwl disconnect message (unit sending it automatically to lwl topic when disconnected?)

**Comment by bennybubble** [comment]
Hi,

Yes correct, something like ESPEasy:

![image](https://user-images.githubusercontent.com/1083428/59380963-9baead80-8d5a-11e9-9193-20a2de23709a.png)

More information here [https://parg.co/4Jx](url)

TIA, Ben

**Comment by enesbcs** [comment]
support added in commit https://github.com/enesbcs/rpieasy/commit/8832c754a9c016c2e3d514b6a35a50a0fa901318

**Comment by bennybubble** [comment]
Thanks, updated my systems (2 RPI boards), tested them and it works perfectly!
