### ISSUE TITLE
If WiFi AP disconnect & reconnects RSSI will be invalid

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/rpieasy#72]

**Comment by TD-er** [comment]
Please note that I've seen a lot of R'pi WiFi issues on my Pi boards too.  (for example on my board running OctoPi )
So that may be some issue which may take you a lot of time and it may not be related to your own code.

**Comment by enesbcs** [comment]
Yep, you are right i am unable to reproduce this so i cant solve it.
