### ISSUE TITLE
Question: Sound level

### ISSUE THREAD

**Issue by bennybubble** [enesbcs/rpieasy#74]
Hi,

Not an issue but rather a question:

I'm using the PyGame sound output, works vy nice!
However, how can I change the sound level (as in low..high) for this ?

-ben

**Comment by bennybubble** [comment]
Solved by calling amixer through CLI!

**Comment by enesbcs** [comment]
I've integrated volume changing into RPIEasy just now. Available on the Hardware page and can be setted with the setvolume command.
