### ISSUE TITLE
OLED clearline not working?

### ISSUE THREAD

**Issue by bennybubble** [enesbcs/rpieasy#77]
Hi,

Im using an oled (identified as PCF8574A/SSD1305/SSD1306 monochrome OLED when scanning I2C) to display some text from OpenHab using MQTT.
The text is written to the display (so communication is okay) but when using clearline, the line is not erased!
![Clipboard01](https://user-images.githubusercontent.com/1083428/61187998-30b60680-a679-11e9-9007-974bbfab82fd.png)

Command used to write text : 
   ` rpi047_Cmd.sendCommand("oled,1,0,Alarm ON")`
Command used to erase line : 
   ` rpi047_Cmd.sendCommand("oledcmd,clearline,1")`

Commands as seen in the log file  
```
21:10:08 CMD: oledcmd,clearline,1
21:10:09 CMD: oled,1,0,Alarm ON
```

Just noticed there is an offset when using clearline and writing text, this works now :
```
21:10:08 CMD: oledcmd,clearline,2
21:10:09 CMD: oled,1,0,Alarm ON
```

So it looks like a bug.

-ben

**Comment by enesbcs** [comment]
You are right it is a bug, but not in clearline, but in the oled write command which is not meant to be 0 based... so "oled,1,0" wrote the wrong line. It is now fixed in commit https://github.com/enesbcs/rpieasy/commit/a95e7710be59b5b9b056ad30794425a3b4210d93

**Comment by bennybubble** [comment]
Tnx, tested and working okay!
