### ISSUE TITLE
Show JSON button under tools

### ISSUE THREAD

**Issue by happytm** [enesbcs/rpieasy#81]
Looks like Show JSON button under tools menu in UI is not responding.

Thanks

**Comment by enesbcs** [comment]
I've just tested it's working for me with 2 enabled Protocols (ESPEasy P2P&Domoticz MQTT) with the following 13 used devices: DHT11, BH1750, Output helper, Run OS command, System Info, Pygame Sound Player, VLC Sound PLayer, Dual Switch device, Input Switch device, Dummy device, Pygame Sound Background player, Input Evdev.

Please send me your configuration to be able to debug.

**Comment by Budman1758** [comment]
I have 2 different units running. One using build  0.19.176  and the other using build  0.19.208  and both of them are working as they should.

**Comment by happytm** [comment]
OK it is working now. I think I had build 0.19.207 running but instead of updating whole firmware I just replaced the commands.py file on pi. Now I notice update button under tools which makes it so easy. Once I updated to latest build it is working fine.

Sorry for the trouble.

Thanks

**Comment by enesbcs** [comment]
Thanks for feedback, it was a bug that had been fixed before. :)
