### ISSUE TITLE
Missing Controller: Generic HTTP

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#91]
Hi,
It miss controller:  Generic http.
it is useful to use it with Jeedom.

Thank's.

Ludo.

**Comment by enesbcs** [comment]
Hi,
You mean C008 controller?
https://github.com/letscontrolit/ESPEasy/blob/mega/src/_C008.ino

**Comment by llevet** [comment]
Hi Alexander,

Yes, exactely.

Ludo.

**Comment by enesbcs** [comment]
C008 controller for simple GET HTTP request is now implemented. Authentication is not yet supported,  %sysname%, %tskname%, %valname% and %value% is supported like the original.

**Comment by llevet** [comment]
Hi,
Perfect ! It is working ! 

Please, normaly for jeedom (plugin espeasy) the url for Controller Publish is : 
device=%sysname%&taskid=%id%&cmd=%valname%&value=%value%

We use taskid number (%id%) and not  %tskname%.
I put it to 0 like this (i see on my esp8266 that %id% return 0 or 1 but alway the same value) :  
device=%sysname%&taskid=0&cmd=%valname%&value=%value%
and it work well. I don't know if it is important or not, but it work like that.

Thank's a lot.

Ludo.

**Comment by enesbcs** [comment]
Sure, I can add %id% that will be the number of the task 1..48.

**Comment by llevet** [comment]
Hi,
Perfect it work.
Thank's.

Ludo.
