### ISSUE TITLE
Missing Pulse GPIO command

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#93]
Hi,

Please could you add Pulse for GPIO like this : 
https://www.letscontrolit.com/wiki/index.php?title=GPIO

Thank's.

Ludo.

**Comment by enesbcs** [comment]
Please add a P001 or a P029 plugin, and gpio,pwm,pulse,longpulse,tone,rtttl commands will be available as it worked in the original ESPEasy versions. This is the only method i can offer.

**Comment by llevet** [comment]
Hi,
Excuse, i make a typo during my test (on P029 plugin), so i have think it wasn't implemented.

Ludo.
