### ISSUE TITLE
Plugin P001 Input - Switch Device/Generic GPIO adding Switch Button Type

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#96]
Hi,

Could you add ,if it is possible with python, the "Switch Button Type:"
- Normal switch
- Push Button Active Low
- Push Button Active High

Thanks.

Ludo.

**Comment by enesbcs** [comment]
Ok, it can be done.

**Comment by enesbcs** [comment]
Its implemented in commit https://github.com/enesbcs/rpieasy/commit/238fda597d4918e6ba8533a5cc508ba51158868b

**Comment by enesbcs** [comment]
Return value mismatch addressed in commit https://github.com/enesbcs/rpieasy/commit/14875c558a4a5acc4ca8ba1ce97d4c07d6feb415

**Comment by llevet** [comment]
Working without problem.

Thank's.
