### ISSUE TITLE
Add HTTP Status of GPIO

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#97]
Please add command (status) to return a Json state of GPIO.
(https://www.letscontrolit.com/wiki/index.php/ESPEasy_Command_Reference)

Example :
http://X.X.X.X/control?cmd=status,gpio,16

return :

{
"log": "",
"plugin": 1,
"pin": 16,
"mode": "input",
"state": 0
}

**Comment by enesbcs** [comment]
Status command introduced in commit https://github.com/enesbcs/rpieasy/commit/0417591c885769b01160e45b2834257da3713598

**Comment by llevet** [comment]
Nice.
can you add CR on each line ? Actualy is all inline, And replace ' by " like ESPeasy.

{
"log": "",
"plugin": 1,
"pin": 10,
"mode": "input",
"state": 0
}
instead of : 
{'plugin': 0, 'pin': 16, 'mode': 'input', 'state': -1}

Thanks.

**Comment by llevet** [comment]
Also, it miss log.
When you send a GPIO command, the "log" is explicite like that :
wget http://172.31.31.138/control?cmd=GPIO,17,1 
{
"log": "GPIO 15 Set to 1",
"plugin": 1,
"pin": 15,
"mode": "output",
"state": 1
}

If it is a simple status, the log is "" : 
wget http://172.31.31.134/control?cmd=status,gpio,15
{
"log": "",
"plugin": 1,
"pin": 15,
"mode": "output",
"state": 0
}

**Comment by enesbcs** [comment]
Sure i can replace single quotes to double, and adding CR is also possible.

I skipped "log" because i did not know what is the use of it.. and i still dont know what can i ever use it? If you issue a command, you know what you asked for.

**Comment by enesbcs** [comment]
Status command output changed in commit https://github.com/enesbcs/rpieasy/commit/59c210ee89f96fbd638fe92f6697e9f1a0ce98e8

**Comment by enesbcs** [comment]
Fixed in commit https://github.com/enesbcs/rpieasy/commit/3d8bf11e5d9f3220822fe9f65c4adeb0e8d1482a

**Comment by llevet** [comment]
Perfect it's working.
