### ISSUE TITLE
Add support for MCP23008 in plugin P009

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#98]
Hi,

Hi, thanks to add support for MCP23008 to th plungin _P009_MCP.

Ludo.

**Comment by enesbcs** [comment]
Selectable type option added in commit https://github.com/enesbcs/rpieasy/commit/0417591c885769b01160e45b2834257da3713598

**Comment by llevet** [comment]
Thanks, i will test it.
You can rename the plugin to : P009 - Extra IO - MCP230xx

**Comment by enesbcs** [comment]
Only if works.. :D

**Comment by llevet** [comment]
So,
Set output GPIO is ok :
http://172.31.31.138/control?cmd=MCPGPIO,2,0
http://172.31.31.138/control?cmd=MCPGPIO,2,1

If i put 1 GPIO to input with MCP interrupt to something, all other MCPGPIO change to the same MCP interrupt (input or output) and i can't remove it or replace it by a other pin.

Command to read status of MCPGPIO from http doesn't existe.

**Comment by llevet** [comment]
![MPC23008](https://user-images.githubusercontent.com/13711825/66278096-64828000-e8a6-11e9-948b-5d49df6a2d3e.PNG)

**Comment by enesbcs** [comment]
>If i put 1 GPIO to input with MCP interrupt to something, all other MCPGPIO change to the same >MCP interrupt (input or output) and i can't remove it or replace it by a other pin.
This is the way how the MCPGPIO driver works, it is using exactly ONE GPIO on the Raspberry to report changes from it's own pins.

> Command to read status of MCPGPIO from http doesn't existe.
This is why the first place the whole Controller architecture was involved... otherwise you can make your own rules to do anything you wish upon status changes like 
`on mpc-input-pin1#State do ... endon`

**Comment by llevet** [comment]
1 - I agree that you have 1 GPIO (interupt line) for all the pins on the chip. But the problem is i can't change it on the fly. To change it, i need to delete all task and remake it...

2 - On my test, interupt line change only the status of input line. If i use this rule : 

on mpc-input-pin-3#state=1 do
   if [mpc-output-pin-2#state]=1
       MCPGPIO,2,0
   else
       MCPGPIO,2,1
   endif
endon

each time it go to MCPGPIO,2,1 branch. mpc-output-pin-2 state is 0 but in reality it is 1.

3 - And in final, calculation of adresss base (0x20 ..) doesn't work for MPC23008.
I put 2 MPC23008 and the interr
![2xMPC23008](https://user-images.githubusercontent.com/13711825/66317416-c0d2b780-e919-11e9-9bac-c6d989aea63d.PNG)
upt is the same (put automatically) for the two chip.
 
In fact, it will be very dificult for you to calculate the ship adresse of electronic component.
Imagine i use 1 MPC23008 and 1 MPC23017. 
So you can't calculate all possibility port: 
MPC23008 MPC23017 => 1-8 9-24
MPC23017 MPC23008 => 1-16 17-24
MPC23017 MPC23017 => 1-16 17-32
MPC23008 MPC23008 => 1-8 9-16
and this is only for 2 , think with more (max is 8) ...
Maybe the best is to put directly the address base on the interface like P023 with pulldown values : 0x20 0x21 .... 0x27 and not calculate it.
With that, it is easier to affect interrupt GPIO to each address base.

Sorry for all work i ask to you ....

**Comment by enesbcs** [comment]
> 1 - I agree that you have 1 GPIO (interupt line) for all the pins on the chip. But the problem is i can't change it on the fly. To change it, i need to delete all task and remake it...

I do not see any reason why you can not change an interrupt - if you choose a correctly configured one (input,input-pullup, input-pulldown). The plugin tries to set it every time you press Submit.

> 2 - On my test, interupt line change only the status of input line. If i use this rule :
> 
> on mpc-input-pin-3#state=1 do
> if [mpc-output-pin-2#state]=1
> MCPGPIO,2,0
> else
> MCPGPIO,2,1
> endif
> endon
> 
> each time it go to MCPGPIO,2,1 branch. mpc-output-pin-2 state is 0 but in reality it is 1.

It is possible as outputs are not followed. I will look it up.

> 3 - And in final, calculation of adresss base (0x20 ..) doesn't work for MPC23008.
> I put 2 MPC23008 and the interrupt is the same (put automatically) for the two chip.
> 
> In fact, it will be very dificult for you to calculate the ship adresse of electronic component.
> Maybe the best is to put directly the address base on the interface like P023 with pulldown values : 0x20 0x21 .... 0x27 and not calculate it.
> With that, it is easier to affect interrupt GPIO to each address base.
> 
> Sorry for all work i ask to you ....

I am a little confused... you write an hour ago that you want to "stick to Espeasy behaviour"
https://www.letscontrolit.com/wiki/index.php/MCP23017
First extender starts from port 1, second starts from 17, third from 33 and so on. Regardless of its type. This is the current behaviour and the simplest one. If you use an MCP23008 you simply lose 8 ports, if you need these ports you have to buy an MCP23017. So MCP2 starts from 17 not from 9 as you thought. The interrupt will surely be the same for port 1-16 and a new interrupt can be assigned to 17-32.

**Comment by llevet** [comment]
1 - I'm talking about changing : MCP interrupt. It is sticky to my first choice, can't change this GPIO. At validation, each time the old value is back.

3 - Nice ! I haven't think to that ! 
Add in source code documentation that in case of using MCP23008 the port count is the same as if we use a MCP23017.  

But the problem of MCP interrup is steel present. It put automatically the MCP interrupt of the first chip, no change is possible :
![2xMPC23008_new](https://user-images.githubusercontent.com/13711825/66324519-ea91db80-e925-11e9-83e6-d1db32e52df6.PNG)

**Comment by enesbcs** [comment]
In commit https://github.com/enesbcs/rpieasy/commit/3d8bf11e5d9f3220822fe9f65c4adeb0e8d1482a the GPIO changing is more easier, but only the first task can change it per device.
Now the plugin value state will follow output state. (At least I hope, because i have used my only one MCP for an ESP8266 long time ago, so i am unable to test it with an RPI.)

**Comment by llevet** [comment]
Ok it is working now to change the MCP interrup and the second ship can have his own.

![MCP_OK](https://user-images.githubusercontent.com/13711825/66339685-ed9bc480-e943-11e9-944a-0ca044c82feb.PNG)

I will check the output state after (i need to push button but i can't make this remotely :-)

**Comment by llevet** [comment]
Nice ! The follow output test is working ! My rule work without problem.

Thanks !
