### ISSUE TITLE
Build version incorrectly displayed

### ISSUE THREAD

**Issue by llevet** [enesbcs/rpieasy#99]
This is just cosmetic but build version is not correctly displayed:

In interface we have : 
RPIEasy 0.19.28 
instead of :
RPIEasy 0.19.280

**Comment by enesbcs** [comment]
You are right, the simple division i used for program version calculation from build is not the best approach. :)
However if i modify it, i think it is a good occasion to remove "0" from the front which was added by me at the first commit at Dec 29 2018, to show that the core was in a very-very-very early alpha stage.

**Comment by llevet** [comment]
Agree, this the app is no more in alpha or beta stage.

**Comment by enesbcs** [comment]
Thankx, issue closed for now!
